# -*- coding: utf-8 -*-
"""yelp_data_preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KpQl0jlaxc2t6P7-YLWY0eTFqxFFATWN
"""

import json
input_filenames = ["indian_restaurant_raw.json", "chinese_restaurant_raw.json", "mexican_restaurant_raw.json", "italian_restaurant_raw.json", "japanese_restaurant_raw.json", "korean_restaurant_raw.json"]
output_filenames = ["indian_restaurant.json", "chinese_restaurant.json", "mexican_restaurant.json", "italian_restaurant.json", "japanese_restaurant.json", "korean_restaurant.json"]

for i in range(len(input_filenames)):
  input_file = input_filenames[i]
  print('\nInput File: ',input_file)
  with open(input_file, 'r') as j:
    contents = json.loads(j.read())
  print('Processing...')
  input = contents["values"]
  output = input[0]["value"]
  output_file = output_filenames[i]
  with open(output_file, 'w') as outfile:
    outfile.write(output)
  print('Output File: ',output_file)

